/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionBtn: typeof import('./src/components/ProTable/components/ActionBtn.vue')['default']
    AutoTooltip: typeof import('./src/components/AutoTooltip.vue')['default']
    BtnLoading: typeof import('./src/components/BtnLoading.vue')['default']
    ConfirmBtn: typeof import('./src/components/ProTable/components/ConfirmBtn.vue')['default']
    CusBarChart: typeof import('./src/components/CusBarChart.vue')['default']
    CusLineChart: typeof import('./src/components/CusLineChart.vue')['default']
    CusPieChart: typeof import('./src/components/CusPieChart.vue')['default']
    CusRangePicker: typeof import('./src/components/CusRangePicker.vue')['default']
    FormGenerator: typeof import('./src/components/FormGenerator.vue')['default']
    HeartShape: typeof import('./src/components/HeartShape.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber/index.vue')['default']
    MultipleEllipsis: typeof import('./src/components/MultipleEllipsis.vue')['default']
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    PlusChart: typeof import('./src/components/PlusChart/index.vue')['default']
    ProChart: typeof import('./src/components/ProChart/index.vue')['default']
    ProTable: typeof import('./src/components/ProTable/index.vue')['default']
    RangePickerLimit: typeof import('./src/components/RangePickerLimit.vue')['default']
    RankNum: typeof import('./src/components/ProTable/components/RankNum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/ProTable/components/SearchBox.vue')['default']
    SubTitlePlus: typeof import('./src/components/PlusChart/components/SubTitlePlus.vue')['default']
    VNode: typeof import('./src/components/VNode.vue')['default']
  }
}
